export const nftData = [
    {
        id: 1,
        likes: 4,
        liked: false,
        nftImage: '/img/tmp/nftcard1.jpg',
        nftName: 'Digital Cobalt Blue (AF)',
        crypto: 0.05,
        cryptoName: 'Fantom',
        cryptoLogo: '/img/tmp/fantom.svg',
        timeLeft: '22 hours',
        lastPrice: {
            crypto: 0.05,
            cryptoName: 'Fantom',
            cryptoLogo: '/img/tmp/fantom.svg',
        },
    },
    {
        id: 2,
        likes: 8,
        liked: false,
        nftImage: 'https://picsum.photos/id/237/200/300',
        nftName: 'Digital Cobalt Blue (AF)',
        crypto: 0.05,
        cryptoName: 'Fantom',
        cryptoLogo: '/img/tmp/fantom.svg',
        timeLeft: '22 hours',
        lastPrice: {
            crypto: 0.05,
            cryptoName: 'Fantom',
            cryptoLogo: '/img/tmp/fantom.svg',
        },
    },
    {
        id: 3,
        likes: 10,
        liked: false,
        nftImage: 'https://picsum.photos/id/237/400/300',
        nftName: 'Digital Cobalt Blue (AF)',
        crypto: 0.05,
        cryptoName: 'Fantom',
        cryptoLogo: '/img/tmp/fantom.svg',
        timeLeft: '22 hours',
        lastPrice: {
            crypto: 0.05,
            cryptoName: 'Fantom',
            cryptoLogo: '/img/tmp/fantom.svg',
        },
    },
    {
        id: 4,
        likes: 15,
        liked: false,
        nftImage: 'https://picsum.photos/id/237/800/400',
        nftName: 'Digital Cobalt Blue (AF)',
        crypto: 0.05,
        cryptoName: 'Fantom',
        cryptoLogo: '/img/tmp/fantom.svg',
        timeLeft: '22 hours',
        lastPrice: {
            crypto: 0.05,
            cryptoName: 'Fantom',
            cryptoLogo: '/img/tmp/fantom.svg',
        },
    },
    {
        id: 5,
        likes: 15,
        liked: false,
        nftImage: 'https://picsum.photos/id/237/800/400',
        nftName: 'Digital Cobalt Blue (AF)',
        crypto: 0.05,
        cryptoName: 'Fantom',
        cryptoLogo: '/img/tmp/fantom.svg',
        timeLeft: '22 hours',
        lastPrice: {
            crypto: 0.05,
            cryptoName: 'Fantom',
            cryptoLogo: '/img/tmp/fantom.svg',
        },
    },
];
